### ISSUE TITLE
Async/await support for Guard/Transition methods

### ISSUE THREAD

**Issue by dmumladze** [appccelerate/statemachine#10]
Hi,
Does the PassiveStateMachine support async/await as guard and/or transition methods? Will it work correctly if async/await is used?

// guard method
private async bool GuardThis()
{
     return Task.FromResult(bool);
}

//transition method
private async void TransitionThere()
{
     try
     {
          await MyAwaitableMethod();
     }
     catch (Exception e)
     {
           exceptions.Add(e);
     }
}

Thanks,
David

**Comment by ursenzler** [comment]
Hi David

No, the state machine does not support async/await. I think it makes no sense in the passive state machine, because it would not be passive anymore. Unfortunately, the active state machine does support it neither.

**Comment by August2008** [comment]
No problemo. I can work around it.. Still the best .NET state machine around.

Anyway, why does not it make sense?

**Comment by ursenzler** [comment]
Thanks a lot!

I wrote a long response to explain why async/await does not make sense. Until I convinced myself that I was wrong :-O

I'll discuss this with @danielmarbach , my async/await guru.

**Comment by August2008** [comment]
Sounds good. Let me know the size of the effort (roughly what you think) and I'll see if I have enough resources to contribute...

**Comment by danielmarbach** [comment]
Pull me in if needed

**Comment by ursenzler** [comment]
This one is hard to estimate because the task consists mostly of experimentation.

**Comment by danielmarbach** [comment]
The question is: Are you willing to break the API or not? Because mixing both sync and async APIs is going to end up well. The only reasonable way to do it is by implementing both paths redundantly.

**Comment by danielmarbach** [comment]
If you want go both ways then you have to introduce a new interface like IAsyncStateMachine and corresponding AsyncPassive and AsyncActive versions

**Comment by PaulVipond** [comment]
This is what I started out doing for async, since I preferred my states method to be async:

'''
            _accountMachine.In(AccountStateType.AwaitingTransfer)
                //.PermitReentry(AccountStateTrigger.RequestAccountTransfer)
                .ExecuteOnEntry(async (AccountTransferConfirmRequest r) => await this.stateFired_Active_viaAccountTransferConfirm(r))
                .On(AccountStateTrigger.ConfirmAccountTransfer).Goto(AccountStateType.Active);
'''

I take it I'm going to run into problems, though it does compile? At face value, it seemed to be working OK, but I have run into one issue, which I'm going to raise separately and I don't think is related..

**Comment by danielmarbach** [comment]
@PaulVipond it compiles yes. But this has a huge problem. The delegate you are now using is `async void`. Any exception raised by the invocation cannot be observed by the statemachine. From the statemachine perspective this is a fire & forget call. This can lead to subtle production issues. I strongly recommend NOT to use this approach

**Comment by PaulVipond** [comment]
@danielmarbach Thanks for the advice - I had wondered whether any exceptions would surface, so it's good to be clear that they won't! I really want my state methods to be asynchronous, so I think I'll wrap them all in an initial try / catch, and make sure my logging is beefy enough to cope. They're already returning results through private members on the class, so that part's OK.

**Comment by ursenzler** [comment]
Just to let you know, that I started to implement a state machine that supports async await. 
You can find the current state of development at https://github.com/appccelerate/statemachine/tree/async.

**Comment by dmumladze** [comment]
Thanks for adding async/await support!
