### ISSUE TITLE
State machine initialisation

### ISSUE THREAD

**Issue by PaulVipond** [appccelerate/statemachine#11]
Hi Urs,

I'm in the preliminary stages of working with your library, and very nice it is too. I'm using it to simplify the account registration process for my app, which has a number of different states and ways of transitioning between them. 

The question I have is: is there any way around the initial state firing when the machine is started? In my case, the state machine is not long running: it's initialised for every account API interaction (registration, transfer, cancellation, verification etc), and then discarded immediately. This means that the initial state has already fired and I'm interested in the transition to the next state triggered by the current request. Obviously, I'm persisting the state in between requests, but outside of the state machine. To put this in code perspective:

```
            _accountMachine = new PassiveStateMachine<AccountStateType, AccountStateTrigger>("Account");

            _accountMachine.In(AccountStateType.Unregistered)
                .On(AccountStateTrigger.RegisterAccount)
                    .If(() => stateCheck_registrationsSuspended()).Goto(AccountStateType.AwaitingSiteRegistrationsTurnedOn)
                    .If(() => !(stateCheck_registrationsSuspended()) && stateCheck_paidRegistrations()).Goto(AccountStateType.AwaitingPayment)
                    .If(() => !(stateCheck_registrationsSuspended()) && !(stateCheck_paidRegistrations())).Goto(AccountStateType.AwaitingVerification);

            _accountMachine.In(AccountStateType.AwaitingVerification)
                .ExecuteOnEntry<RegistrationRequest>(async (RegistrationRequest r) => await this.stateFired_AwaitingVerification_viaRegistration(r))
                .ExecuteOnEntry<VerificationRequest>(async (VerificationRequest r) => await this.stateFired_AwaitingVerification_viaVerification(r))
                .ExecuteOnEntry(() => ())
                .On(AccountStateTrigger.RegisterAccount)
                    .If(() => stateCheck_registrationsSuspended()).Goto(AccountStateType.AwaitingSiteRegistrationsTurnedOn)
                    .If(() => !(stateCheck_registrationsSuspended()) && stateCheck_paidRegistrations()).Goto(AccountStateType.AwaitingPayment)
                    .If(() => !(stateCheck_registrationsSuspended()) && !(stateCheck_paidRegistrations())).Goto(AccountStateType.AwaitingVerification)
                .On(AccountStateTrigger.VerifyAccount)
                    .If(() => !stateCheck_verificationAttemptsExhausted() && !stateCheck_verificationCodesMatch()).Goto(AccountStateType.AwaitingVerification)
                    .If(() => !stateCheck_verificationAttemptsExhausted() && stateCheck_verificationCodesMatch()).Goto(AccountStateType.Active)
                    .If(() => stateCheck_verificationAttemptsExhausted()).Goto(AccountStateType.VerificationFailed);

            _accountMachine.Initialize(AccountStateType.Unregistered);
            _accountMachine.Start();
            _accountMachine.Fire(AccountStateTrigger.RegisterAccount, req);  // Passing RegistrationRequest 
```

I get error: `Cannot cast argument to match action method. Argument = ...Contracts.RegistrationRequest, Action = anonymous` because I think the state machine doesn't have an `ExecuteOnEntry()` method defined for `AccountStateType.Unregistered` and is trying to match the `RegistrationRequest` signature when I fire the `RegisterAccount` trigger. Essentially, I'd like the state machine to consider the state passed in `Initialize()` as a bootstrap directly to that state without seeking to trigger any events associated to that state. I hope this makes sense.

**Comment by PaulVipond** [comment]
So I looked at the Load() persistence call to see if that would 'swallow' the first state, but it seems the same thing is happening. Assuming I'm not missing something obvious, what would be the best way to provide this? An optional boolean to the Initialize method indicating whether to raise the initial event, or a StartWithNoInitialEvent() method? Happy to mod and create a pull request if you let me know.

**Comment by PaulVipond** [comment]
Although having trouble with compilation:

![image](https://cloud.githubusercontent.com/assets/403385/19024673/3f5e5212-8900-11e6-8fda-9f65fbab4f7a.png)

**Comment by ursenzler** [comment]
I'm on vacation this week and I don't habe a good way to look at your code right now. 

The cast exception probably results from the fact that you pass something to Fire that does not match what you expect in an action method. The types must match (or at least be assignable). 

There is no way around initializing the initial state. I think that would not be a good idea anyway because it could lead to inconsistent state machines. Can't you just use the initial state without any entry action?
