### ISSUE TITLE
Not compatible with .NET 4.0

### ISSUE THREAD

**Issue by fgroes** [appccelerate/statemachine#14]
When trying to install with nuget package manager

Could not install package 'Appccelerate.Fundamentals 2.8.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Which Framework version do you support? I could not find the info on the documentation site.

**Comment by philippdolder** [comment]
For the Full Framework the latest appccelerate versions support .NET 4.5 and newer.

My first suggestion would be to update your .NET Framework to stay up-to-date.
If that's not possible you can use https://www.nuget.org/packages/bbv.Common.StateMachine/ which is the old (no longer maintained) version of appccelerate.

@ursenzler can you verify this?

**Comment by fgroes** [comment]
Yes, it works with .NET 4.5. I would suggest to add that info somewhere in the documentation, either in nuget or the documentation homepage.
