### ISSUE TITLE
4.0 Nuget package looks to still be 3.3 without async

### ISSUE THREAD

**Issue by lscpike** [appccelerate/statemachine#18]
I was looking for the AsyncPassiveStateMachine but it looks like your 4.0 package doesn't contain it. The assembly is tagged 3.3.

**Comment by lscpike** [comment]
Also worth mentioning the I can't build the full source as the tests depend on un-published package versions of Appccelerate.Development.

**Comment by ursenzler** [comment]
Yes, you are right, the content of the package is wrong. I'll have to check how that could happen?!!?!?

**Comment by ursenzler** [comment]
Thanks for the tip for Task.CompletedTask. I'll try this.

In the mean time I found the reason why the wrong assembly is in the package. The folder path is wrong in the nuspec file.

I'll also push the development package to nuget.org (in the mean time you can find it on the myget feed [see www.appccelerate.com]).

I'll fix this all tomorrow, thanks very much for reporting these issues.

I'm still struggling with the switch to .net standard :-)

**Comment by lscpike** [comment]
Ah, I've discovered the myget feed for dev deps. Thanks! Yeah I still don't fully understand .net standard.

**Comment by ursenzler** [comment]
I pushed the development packages to nuget.org.

I pushed a new version of the state machine targeting .net standard 1.0 containing the correct assembly to nuget.org.

It should be listed shortly. The version is 4.4.0.

Thanks again for reporting the issues.

**Comment by lscpike** [comment]
Looking good. Thanks very much!
