### ISSUE TITLE
AsyncPassiveStateMachine crash

### ISSUE THREAD

**Issue by PatrickKunz** [appccelerate/statemachine#20]
We had a crash with the async state machine and i'm not sure what the problem is. Here is the stack trace:

```
Object reference not set to an instance of an object.

Stack Trace:
   at System.Collections.Generic.LinkedList`1.InternalRemoveNode(LinkedListNode`1 node)
   at Appccelerate.StateMachine.AsyncPassiveStateMachine`2.<ProcessQueuedEvents>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Appccelerate.StateMachine.AsyncPassiveStateMachine`2.<Execute>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Appccelerate.StateMachine.AsyncPassiveStateMachine`2.<Fire>d__27.MoveNext()
```

Any help is welcome :)

edit: Looks like a multi-threading issue. I was not able to reproduce it so far. Looks like the state machine removed a fire event while iterating through the collection while adding a new fire event. Just a guess...

**Comment by ursenzler** [comment]
Hi Patrick

The AsyncPassiveStateMachine is not thread-safe. You have to make sure that the state machine is not called from different threads.

There is no AsyncActiveStateMachine yet because this is more difficult to get right (from the perspective of how the interface should look and be used).

For the time being, if you really need an active state machine, use the ActiveStateMachine without async.

Hope that explains it.

Happy coding
Urs

**Comment by PatrickKunz** [comment]
Hi Urs

Thanks for the quick answer! This makes sense. So, back to start... Hope the AsyncActiveStateMachine is coming soon :)

Best,
Patrick

**Comment by PatrickKunz** [comment]
Hi Urs

Me again. I just had a look at the code. Does it really make sense to have an AsyncActiveStateMachine?
The passive state machine also changes the threads. You maybe also get issues if some calls are not awaited.
Isn't it possible to just add a SemaphorSlim(1) lock inside the Fire(), FirePriority() and _this.events.RemoveFirst();_?

**Comment by ursenzler** [comment]
Good question. And I don't know the answer to it. I'll have to think about it.

I'm not sure if putting a semaphore around the code you suggested is enough.
What about the current state variable?

**Comment by PatrickKunz** [comment]
One small disadvantage of the semaphore is that it's disposable and the whole state machine needs to be disposed. But i think i could live with that in this case :)

Not sure about the state variable. Maybe it also needs a task queue to process the states in sequence. I have to take a closer at the code...

**Comment by ursenzler** [comment]
fyi: the AsyncActiveStateMachine is under development. As well as the making of a thread-safe AsyncPassiveStateMachine.

**Comment by PatrickKunz** [comment]
Great, thanks :)

**Comment by ursenzler** [comment]
Should be fixed with https://github.com/appccelerate/statemachine/pull/26 which is merge to master and available as a pre-release package in nuget
