### ISSUE TITLE
YEdStateMachineReportGenerator produce an invalid xml/graphml file (namespace SchemaLocation)

### ISSUE THREAD

**Issue by djack42** [appccelerate/statemachine#23]
There is an invalid xml namespace in the generated output from the `YEdStateMachineReportGenerator`

The value of `SchemaLocation` is wrong :
`private static readonly XNamespace SchemaLocation = "http://graphml.graphdrawing.org/xmlns http://www.yworks.com/xml/schema/graphml/1.1/ygraphml.xsd";`

The first part is probably a wrong paste from the namespace `N` and the value should be :
`private static readonly XNamespace SchemaLocation = "http://www.yworks.com/xml/schema/graphml/1.1/ygraphml.xsd";`

**Comment by ursenzler** [comment]
How did you find this error? I used the report many times, without an issue.

It's fixed now anyway. Many thanks. Will be released with your other reported issue.

**Comment by djack42** [comment]
A simple xml validation in notepad++, and Yed Live wouldn't load it.

**Comment by ursenzler** [comment]
Didn't know there was an in-browser version, nice. Thanks.

**Comment by ursenzler** [comment]
The fix is on master and available in the pre-release package on nuget
