### ISSUE TITLE
Parametrized Entry Actions

### ISSUE THREAD

**Issue by adpaglia** [appccelerate/statemachine#27]
Hi,

using:

  bbv.Common.StateMachine (v.7.4.12149.1635)
  bbv.Common.AsyncModule (v.7.2.12149.1635)
  bbv.Common (v.7.1.12149.1635)

I'm trying to use a parametrized entry action. The documentation on the Appcelerate website states that it is possible to use the following syntax:

```
stateMachine.In(States.A)
     .ExecuteOnEntry<string>(this.SomeMethodWithStringArgument);
```

Now I'm having the following action:

```
private void StateOnEntryOperations(Dictionary<int, string> pars)
{
      DoActions(pars);
}
```

And I'm defining my state A:

```
_stateMachine.In(States.A)
     .ExecuteOnExit<Dictionary<int, string>>(StateOnEntryOperations);
```
trying to fire the transition to state A:

```
private void FireStateA()
{
      Dictionary<int, string> dictionary = new Dictionary<int, string>();
      // Add elements to dictionary...
      Machine.Fire(Events.TriggerForStateA, dictionary);
}
```

I need the argument to be passed from method FireStateA().
What I get is a compiler error forcing me to use:

`.ExecuteOnEntry(Action<Dictionary<int, string>> action, Dictionary<int, string> parameter)`

If I understand properly I should use a compiled and not dinamically generated parameter:

```
stateMachine.In(States.A)
     .ExecuteOnExit<Dictionary<int, string>>(StateOnEntryOperations, new Dictionary<int, string>());
```
but is would be always empty...

Am I missing something? Is there any other syntax allowing me to do what I need?

Thanks in advance

Alberto

**Comment by ursenzler** [comment]
Hi Alberto

Nothing obviously wrong here.

Suggested steps:

1. update to the current version of Appccelerate.StateMachine (bbv.Common.StateMachine is really old and I can't remember how things are handled there anymore) and see if the problem still exists.

1. What is the compile error you mentioned? The overload with the parameter as a second argument should not be used in your scenario.

1. Provide me with a small solution that reproduces the problem.

Urs

**Comment by adpaglia** [comment]
Hi Urs, 

many thanks for your really quick answer. 
I was definitely also too quick, but in selecting the older NuGet package version... 
I did not check the release date but was attracted by the higher version number. Sorry for that. 

I will immediately switch to the more recent files and probably everything will be OK. 
Just in case, can I use the address Urs Enzler" <notifications@github.com> to recontact you, or do I have to update the issue opened on GitHub: actually it is not an issue at all.. 

Thanks again and Merry Christmas and Happy New Year. 

Cheers 

Alberto 

EuroVector S.r.l. 
Via F.lli Cuzio, 42 
27100 Pavia (PV) - Italy 
Tel: +39.0385.747010 
web: https://www.eurovector.it

**Comment by ursenzler** [comment]
Hi Alberto

Please answer the issue. Otherwise, your whole email signature gets added to the issue. I removed your details from the issue so you don't get spammed.

Let's hope it works.

Merry Christmas and Happy New Year to you, too! Thanks!!
Urs

**Comment by adpaglia** [comment]
Hi Urs,
I have referenced the correct Appcelerate dlls and everything is working smoothly now.
Thanks again
Cheers
Alberto
