### ISSUE TITLE
Microservices orchestrator

### ISSUE THREAD

**Issue by VenkateshSrini** [appccelerate/statemachine#29]
Hi,

I'm interested in building something like Azure logic app or Netflix microservice orchestrator. For this I need to load workflow from a JSON file or XML file from a workflow designer. Is that possible with this library

**Comment by ursenzler** [comment]
Hi,

No, not out of the box. This library uses a fluent syntax to define the state machine.

Cheers,
Urs

**Comment by VenkateshSrini** [comment]
ok thanks
