### ISSUE TITLE
NuGet Dependencies Request > 2.1; however, build then produces different version warnings

### ISSUE THREAD

**Issue by mrwizard82d1** [appccelerate/statemachine#3]
I've been working with the Appccelerate state machine component for several months now. 

When I downloaded the latest component using NuGet (version 2.7), I saw no errors during the NuGet install. During the build, I received a warning about different versions of dependent assemblies. Most importantly, when I ran my unit tests, I received the following error:

Result Message:	System.IO.FileNotFoundException : Could not load file or assembly 'Appccelerate.Fundamentals, Version=2.7.0.0, Culture=neutral, PublicKeyToken=917bca444d1f2b4c' or one of its dependencies. The system cannot find the file specified.

When NuGet installed the state machine component, I recall that it requested version 2.1.0 of Appccelerate.Fundamentals.

What can we do to correct this issue? My work around is to install version 2.7 of the Appcelerate dependent packages by hand.

Thanks for all your hard work. You have saved me much work by all your hard work.

Have a great day!

**Comment by ursenzler** [comment]
Fixed by setting the correct version of the dependency.
