### ISSUE TITLE
Guards after Goto

### ISSUE THREAD

**Issue by mikolaj-milewski** [appccelerate/statemachine#32]
Let's consider following machine:

            var ms = new PassiveStateMachine<string, string>();
            ms.In("a")
                .On("go")
                .If(() => {
                    Console.WriteLine("guard1");
                    return true;
                })
                .Goto("b")
                .If(() => {
                    Console.WriteLine("guard2");
                    return true;
                })
                .Execute(() => Console.WriteLine("transition"));
            ms.Initialize("a");
            ms.Start();
            ms.Fire("go");
            ms.Stop();

What is expected outcome from this? Intuitively, `Goto` is guarded by guard1 and `Execute` by guard2 - however, guard2 is never evaluated and `Execute` action never called. Looks like bug to me.

**Comment by ursenzler** [comment]
The first guard returning true is taken. There is no check whether several guards return true.

See documentation: http://www.appccelerate.com/statemachine.html  (scroll down to Guards).

**Comment by mikolaj-milewski** [comment]
I understand that. My setup is wrong, but it is allowed by the interface. I'd rather prefer not to be able to call `If` after `Goto`, only after `On`. Or maybe I am missing something and `If` is needed to be allowed here for some cases..?

**Comment by ursenzler** [comment]
Ah I see. I didn't realize that the first `On` didn't have a `Goto`.

`On("go").If(x => true)` means that the state machine will do an internal transition and stay inside "a". An internal transition is a transition that does **not** execute exit and entry actions and stays in the same state. You could however specify transition actions to be executed:
`On("go").If(x => true).Execute(FancyStuff)`

Better?

**Comment by mikolaj-milewski** [comment]
I understand concept of in-state-reaction ("internal transition") as well. Still, what is the purpose of `If` after `Goto` in 'scope' of single `On`?

**Comment by ursenzler** [comment]
The `If` after the `Goto` belongs to the next transition definition. In your example above, if the first guard would return false and the second true, the machine would execute an internal transition in state `a` and execute the action defined afterwards.

**Comment by mikolaj-milewski** [comment]
Okay, now I get it - single `On` allows to declare multiple transitions by each `If`.
