### ISSUE TITLE
Implementing unconditioned transition

### ISSUE THREAD

**Issue by zorgoz** [appccelerate/statemachine#35]
I have to write a state machine having a special transition for all states. Let's call it _reset_. If this event is fired, the machine has to go in a predefined state, no matter what the current state is. Of course, I could define this transition for each and every state, but this is what I want to avoid.

I tried to implement it using custom state class, like this (LinqPad query):

```
void Main()
{
	var fsm = new PassiveStateMachine<MyState, Events>()	;
		
	fsm.In(MyState.Any)
		.On(Events.R)
		.Goto(MyState.A);
		
	fsm.In(MyState.A)
		.On(Events.E2)
		.Goto(MyState.B);
		
	fsm.In(MyState.B)
		.On(Events.E1)
		.Goto(MyState.A);

	fsm.TransitionCompleted += (s, a) => $"{a.EventId} : {a.StateId.State} => {a.NewStateId.State}".Dump();
	
	fsm.Initialize(MyState.A);	
	fsm.Start();
	
	fsm.Fire(Events.E2); // E2 : A => B
	fsm.Fire(Events.E1); // E1 : B => A
	fsm.Fire(Events.E2); // E2 : A => B
	fsm.Fire(Events.R); // nothing happens
}

enum Events { R, E1, E2 };

public class MyState: IComparable
{
    public enum States { Any, A, B };
	
	public static MyState A => new MyState(States.A);
	public static MyState B => new MyState(States.B);
	public static MyState Any => new MyState(States.Any);
	
	private MyState(States state)
    {
        this.State = state;
    }
 
    public States State { get; private set; }
 
    public override bool Equals(object obj)
    {
        if (ReferenceEquals(null, obj))
        {
            return false;
        }
         
        if (ReferenceEquals(this, obj))
        {
            return true;
        }
         
        if (obj.GetType() != this.GetType())
        {
            return false;
        }
 
        return this.Equals((MyState)obj);
    }
 
    public override int GetHashCode()
    {
        return this.State.GetHashCode();
    }
 
    public int CompareTo(object obj)
	{
		throw new InvalidOperationException("state machine should not use CompareTo");
	}

	protected bool Equals(MyState other)
	{
		return this.State == States.Any || other.State == States.Any || this.State == other.State;
	}
}
```

The universal state `Any` would be equal to any state. Still, in the last statement, when `R` is fired, the `MyState` class is not touched at all. None of the overridden methods is called.

Q1) Why is that?
Q2) Is there any other way to achieve my goal?

**Comment by ursenzler** [comment]
I‘m on vacation and on a very bad internet connection, so barr with me for only a short response. 

You don’t need the MyState class, sinply use the nested state enum as the state variable. 

To have a transition from all states to reset, add a super state that contains all other states as children and define the transition from this super state to the state you want to machine to go. 

For more info see the documentation at www.appccelerate.com —> state machine —> hierarchical state machine. 

Hope that helps
Urs

**Comment by zorgoz** [comment]
This solves it. Thank you.
