### ISSUE TITLE
Move IState, IStateMachineReport, Transitions to Infrastructure (or other) namespace.

### ISSUE THREAD

**Issue by frankhommers** [appccelerate/statemachine#38]
I am writing my own Report Generator. I want it to be able to report on AsyncMachines as well as Non Async Machines. Now I need to copy/paste the class because the only thing that differs between them is the namespace. I think some stuff needs to be moved around so that Async and non Async Machine uses the same IState, IStateMachineReport, Transitions and maybe others I forgot.

What do you think?

**Comment by ursenzler** [comment]
Yes, that is a problem. Some types are equal, some types differ slightly in their signatures. I have no idea, how to solve this elegantly.

**Comment by frankhommers** [comment]
I would start by putting the types that have the same sig in the same namespace. That would solve a lot.

**Comment by frankhommers** [comment]
Unfortunately for this project I moved to Stateless. Maybe in the future I will reconsider this.
