### ISSUE TITLE
AsyncActiveStateMachine.Fire Task never completes

### ISSUE THREAD

**Issue by twodogmbh** [appccelerate/statemachine#42]
The AsyncActiveStateMachine internally uses TaskCompletionSource without the option TaskCreationOptions.RunContinuationsAsynchronously.
This can lead to situations where the Task on the Fire method never completes when the ExecuteOnEntry method blocks.

By default, when this TaskCreationOption is not set the continuations after awaiting the TaskCompletionSource.Task are executed synchronously on the same thread that has called the TaskCompletionSource.SetResult method. This is in my opinion not the expected behavior of a asynchronous active state machine.

Fix:
In the class AsyncActiveStateMachine on line 39 and line 253 create the TaskCompletionSource with the parameter TaskCreationOptions.RunContinuationsAsynchronously (e.g. "new TaskCompletionSource<bool>(TaskCreationOptions.RunContinuationsAsynchronously)")

Here an example which simulates this issue:
The Fire method task never completes.

    public enum State
    {
        FooState1,
        FooState2,
    }

    public enum Event
    {
        FooEvent,
    }

    public class Program
    {
        private static AsyncActiveStateMachine<State, Event> stateMachine;

        static async Task Main()
        {
            Console.WriteLine($"Started (Thread: {Thread.CurrentThread.ManagedThreadId})");

            stateMachine = new AsyncActiveStateMachine<State, Event>();
            stateMachine
                .In(State.FooState1)
                    .ExecuteOnEntry(OnFooState1)
                    .On(Event.FooEvent).Goto(State.FooState2);

            stateMachine
                .In(State.FooState2)
                .ExecuteOnEntry(OnFooState2);

            Console.WriteLine($"Before Initialized (Thread: {Thread.CurrentThread.ManagedThreadId})");
            await stateMachine.Initialize(State.FooState1).ConfigureAwait(false);
            Console.WriteLine($"After Initialized (Thread: {Thread.CurrentThread.ManagedThreadId})");

            Console.WriteLine($"Before Start (Thread: {Thread.CurrentThread.ManagedThreadId})");
            await stateMachine.Start().ConfigureAwait(false);
            Console.WriteLine($"After Start (Thread: {Thread.CurrentThread.ManagedThreadId})");

            await Task.Delay(TimeSpan.FromSeconds(1)).ConfigureAwait(false);

            Console.WriteLine($"Before Fire Event 1 (Thread: {Thread.CurrentThread.ManagedThreadId})");
            await stateMachine.Fire(Event.FooEvent).ConfigureAwait(false);
            Console.WriteLine($"After Fire Event 1 (Thread: {Thread.CurrentThread.ManagedThreadId})");

            Console.WriteLine($"Done (Thread: {Thread.CurrentThread.ManagedThreadId})");

            Console.ReadKey();
        }

        private static async Task OnFooState1()
        {
            Console.WriteLine($"In State 1 (Thread: {Thread.CurrentThread.ManagedThreadId})");
        }

        private static async Task OnFooState2()
        {
            Console.WriteLine($"In State 2 (Thread: {Thread.CurrentThread.ManagedThreadId})");

            // Simulate blocking operation
            while (true) { }
        }

Outcome without "RunContinuationsAsynchronously":

    Started (Thread: 1)
    Before Initialized (Thread: 1)
    After Initialized (Thread: 1)
    Before Start (Thread: 1)
    After Start (Thread: 1)
    In State 1 (Thread: 3)
    Before Fire Event 1 (Thread: 3)
    In State 2 (Thread: 3)

Outcome with "RunContinuationsAsynchronously":

    Started (Thread: 1)
    Before Initialized (Thread: 1)
    After Initialized (Thread: 1)
    Before Start (Thread: 1)
    After Start (Thread: 1)
    In State 1 (Thread: 3)
    Before Fire Event 1 (Thread: 3)
    After Fire Event 1 (Thread: 3)
    Done (Thread: 3)
    In State 2 (Thread: 4)

**Comment by ursenzler** [comment]
Thanks for reporting this! I’ll take a look at this as soon as possible. Probably next week.
