### ISSUE TITLE
No documentation, no unit tests

### ISSUE THREAD

**Issue by philippe-lavoie** [appccelerate/statemachine#58]
Version 5.0 is out and I wanted to use it. However, the documentation site is still referencing the old code and in the repository, there are no unit tests to give me a feel of how to use 5.0. 

Is there a documentation site somewhere ? I want to use a passive machine from command line. 

Thanks

**Comment by philippe-lavoie** [comment]
Alright, managed to stumble upon the fact that Specs is for xbehave specifications, i.e. tests. I'll check those out to migrate my code from 4.0 to 5.0.

**Comment by philippe-lavoie** [comment]
Did you write a migration guide already ?

**Comment by ursenzler** [comment]
Hi philippe-lavoie

I didn't have time yet to update the documentation or to write a migration guide.

You can find examples in the specs or in the pull requests (but they all show only parts of the whole)

Hope that helps you till the documentation is up-to-date again.

Happy coding
Urs

**Comment by ursenzler** [comment]
I added some simple documentation to readme.md
