### ISSUE TITLE
Configure once and create multiple instances...

### ISSUE THREAD

**Issue by djpable** [appccelerate/statemachine#6]
Is it possible to statically initialize a machine and reuse its definition in multiple instances ?

**Comment by ursenzler** [comment]
You typically write a class that holds the definition and all actions. When you create multiple instances of this class you get what you asked for, without "cloning".

See https://github.com/appccelerate/sensorsample/blob/master/source/SensorSample/Sensors/DoorSensor.cs for an example: the DoorSensor uses an Appccelerate.StateMachine in this way. 

The Appccelerate.StateMachine is just the driver, the class holding the instance and providing the action is the actual state machine.

Does this help?

**Comment by djpable** [comment]
Yes, i was implementing my class like that, but it could be interesting to configure the machine once and instantiate that multiple times in different threads.

Could this be a feature request ?

**Comment by ursenzler** [comment]
It surely can be a feature request. This would solve the problem, that the setup is rather slow compared to other libraries (as I was told - didn't find the time to check for myself.

**Comment by ursenzler** [comment]
Finally done in version 5.1.
