### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by 17tmh** [appccelerate/statemachine#67]
Hello,

I want to use the library and wrote an example application with a hierarchical state machine to check it out.
Now I  have a few questions about the current implementation.

1.) When using `builder.DefineHierarchyOn...`, do I always need an initial substate (`WithInitialSubState`).

2.) Is there a way to perform initial actions along with the initial transisions (not entry and exit actions!).

3.) Assume I have:

```
builder.DefineHierarchyOn(States.top)
.WithHistoryType(HistoryType.None)
.WithInitialSubState(States.s1);

builder.In(States.s1).On(Events.eD).Goto(States.top).Execute(() => IOForm.Write("Event D" + Environment.NewLine));
```
On Event eD I get:

s1-Exit
top-Exit
Event D
top-Entry
s1-Entry

Two questions about that:
- Why is the action (here printing "Event D") not performed in state s1 as the code suggests?
- Why are the entry and exit actions of the top state performed at all? I was in state s1, which is a substate of top, so in order to go to top, just going one step up is enough?

Did I misunderstand something oder perhaps I have overlooked conifguration possibilities.

I would be very grateful for an answer.

**Comment by 17tmh** [comment]
Hello,

I have dug a little deeper in the meantime and already found some answers.

What I'm still wondering about is this question:

_Why is the action (here printing "Event D") not performed in state s1 as the code suggests?_

I found out that this behaviour is in accordance with the UML specification but it still doesn't make sense to me. Is there a way to execute actions in the context of the source state (before exiting the source state configuration)? The qp framework is doing it this way. I quote from their documentation:

> One big problem with the UML transition sequence is that it requires executing actions associated with the transition after destroying the source state configuration but before creating the target state configuration. In the analogy between exit actions in state machines and destructors in OOP, this situation corresponds to executing a class method after partially destroying an object. Of course, such action is illegal in OOP. As it turns out, it is also particularly awkward to implement for state machines. Executing actions associated with a transition is much more natural in the context of the
source state—the same context in which the guard condition is evaluated. Only after the guard and the transition actions execute, the source state configuration is exited and the target state configuration is entered atomically. That way the state machine is observable only in a stable state configuration, either before or after the transition, but not in the middle.

**Comment by ursenzler** [comment]
Hi

1) Yes, it is always needed.
2) No, initialisation is a special transition that cannot have actions. If you need to execute something on initialization, I suggest to just call the actions before starting the state machine or with a special Initializing state and transition that you call by queuing an Initialize event on the not yet started state machine.

3) The design of this state machine is as you found out: Exit actions first, then transition actions, finally entry actions.
There is no possibility to change that unless you change the code directly in `TransitionLogic.`

A possibility is that you do not use exit actions, but define the needed actions on the transition after the other transition actions. This would however probably introduce duplication (defining the same action on multiple transitions).

As a side-note that could be related to the reason why you need exit actions to be performed after transition actions:
The states of the state machine should not be visible to the outside (directly). If the surrounding needs to query the state (like is the device on or off) then it is better to reflect this as a property that is toggled by an entry action of the state machine states that contribute to the state visible to the outside.
Let's say we have the following state machine states: DeviceInitializing, Running, ShuttingDown, Off
ShuttingDown would set "On" to true in its entry state.
Off would set "On" to false in its entry state.

Encapsulating "internal" state helps to keep the state machine in a form that is easier to refactor.

I hope that helps you. Let me know.

Happy coding
Urs

**Comment by 17tmh** [comment]
Thanks for your clarification ... and sorry for my late reply.
