### ISSUE TITLE
Cannot test application with state machine using async ExecuteOnEntry action

### ISSUE THREAD

**Issue by zadigus** [appccelerate/statemachine#69]
I am writing a WPF application where I use a state machine which deals with transitions between one screen to the other. 

To do so, I use a `StateMachineDefinitionBuilder`, and part of its configuration looks like this:
```cs
var builder = new StateMachineDefinitionBuilder<ShellState, ShellEvent>();

[...]

builder.In(ShellState.ProfilesInitialization)
                .ExecuteOnEntry(
                    async () =>
                    {
                         await this.profileSelectionViewModel.InitializeProfiles();
                    })
                .On(ShellEvent.GettingProfiles)
                .Goto(ShellState.Busy);

[...]
```

In my production code, I create the state machine like this:
```cs
var defn= builder.Build();
var stateMachine = defn.CreateActiveStateMachine();
```
My production application works like a charm.

Now, when I switch to my tests, I use the very same `builder` as above. Only the creation of the state machine is a bit different:
```cs
var stateMachine = defn.CreatePassiveStateMachine();
```
With that setup in place, my async call above is not awaited in my tests. The only way I've found to make it work in both test and production code is to change the above `ExecuteOnEntry` action to
```cs
() =>
{
    this.profileSelectionViewModel.InitializeProfiles().Wait();
})
```
Is that expected? I was expecting to be able to use async / await and have those calls synchronous with a passive state machine.

**Comment by ursenzler** [comment]
Hi zadigus,
It should work as you expect. 
Could you provide me with a small solution for reproduction? It does not have to be minimal or nice. Just something that I can use for debugging.

Happy coding
Urs

**Comment by zadigus** [comment]
Hi @ursenzler, for some reason I cannot reproduce that problem anymore. I don't know by what magic it disappeared. If it pops up again, I'll let you know.

**Comment by zadigus** [comment]
@ursenzler it seems to be more complicated than I thought. This morning, I was not able to reproduce this issue and now I can repro it again. I need to investigate this further and I'll let you know.

**Comment by ursenzler** [comment]
I wish you luck in finding the cause of the problem!
