### ISSUE TITLE
Compile your awsome library to target .NET 4.6 and Silverlight 5

### ISSUE THREAD

**Issue by jpchauny** [appccelerate/statemachine#7]
Hi,
First of all I want to say that, after searching for libraries that implement State Machines, your library is awesome! The API is simple and fluent and the functionality very powerful.
We want to use your library in a Lightswitch project. To achieve this we must compile your library targeting .NET 4.6 and Silverlight 5 (Portable Class Library).
Is this possible?

**Comment by ursenzler** [comment]
Thanks!

I think that should not be a problem. Why don't you just give it a try and take the source and change the targets of the Appccelerate.StateMachine project?
If there are problems, I can help.

Building is simple, just compile inside visual studio. When in release mode, all tests are run.

For all the automation, please refer to http://www.appccelerate.com/howtocontributecommandlets.html

Happy coding.

**Comment by jpchauny** [comment]
OK. I will give it a try. But there are right now some issues.

The following NuGet packages are not available on nuget.org:

Appccelerate.Development.ProductionCode.Signed v1.21.0
Appccelerate.Fundamentals v3.0.0
Appccelerate.Development.ProductionCode v1.21.0
Appccelerate.Development v1.21.0

Could you please upload them to nuget.org ?

**Comment by jpchauny** [comment]
I found the missing nuget packages here:
https://www.myget.org/F/appccelerate/

But I think it would be easier for everyone to could compile your solution out of the box if the missing nuget packages were in nuget.org...

**Comment by ursenzler** [comment]
There is a nuget.config file in the state machine project that should tell
nuget to get the packages from the myget feed. But obviously, this did not
work :-(

**Comment by ursenzler** [comment]
Did it work?

**Comment by philippdolder** [comment]
@jpchauny you can try the experimental version supporting .NET core. See #9

**Comment by ursenzler** [comment]
The state machine now targets .net Standard 1.0.
