### ISSUE TITLE
Logging documentation

### ISSUE THREAD

**Issue by ChezzPlaya** [appccelerate/statemachine#72]
Please provide a simple log4net logging example.

**Comment by ursenzler** [comment]
You can use an extension for that. See https://github.com/appccelerate/statemachine/blob/nullable_reference_types/documentation/extensions.md

**Comment by ChezzPlaya** [comment]
By example, I've meant a peace of code :). However, I've found out myself, on how to implement a logging extension, which is actually very easy.

Issue closed.
