### ISSUE TITLE
Saving and loading machine state

### ISSUE THREAD

**Issue by pavlexander** [appccelerate/statemachine#77]
How is state saving and loading supposed to work? I see that there are 2 methods available:

```C#
_machine.Save(saver)
_machine.Load(loader)
```

However, it seems like Saver and Loader implementations are not in library... I have searched the repo for `IAsyncStateMachineSaver` and found following 2 implementations `StateMachineSaver<TState, TEvent>` and `StateMachineLoader<TState, TEvent>`:
https://github.com/appccelerate/statemachine/blob/6ae943467fca0472887aefeeeb9d387cb17354f4/source/Appccelerate.StateMachine.Specs/Async/Persisting.cs

Aside from the fact that both classes are not part of the library (you have to re-implement them (or copy to) in your code) - I have doubts that I understand correctly how the saving/loading supposed to work.. I would assume something similar to this is expected?

```C#
var saver = new StateMachineSaver<BotStatesEnum, BotEventsEnum>();
var loader = new StateMachineLoader<BotStatesEnum, BotEventsEnum>();
await _machine.Save(saver);
await _machine.Load(loader);
```

Is there a reason why state could not be simply "saved" and loaded as-is without loaders/savers? So confused..

**Comment by pavlexander** [comment]
Using version: 5.1.0 from Nuget repo, .Net 5 project.

**Comment by pavlexander** [comment]
To make life easier I have written following extension method:

```C#
    public static class AsyncStateMachineExtensions
    {
        public static async Task<StateMachineSaver<T, U>> SaveExt<T, U>(
            this AsyncPassiveStateMachine<T, U> machine)
            where T : IComparable
            where U : IComparable
        {
            var saver = new StateMachineSaver<T, U>();
            await machine.Save(saver);
            return saver;
        }

        public static async Task LoadExt<T, U>(
            this AsyncPassiveStateMachine<T, U> machine, 
            StateMachineSaver<T, U> saver)
                where T : IComparable
                where U : IComparable
        {
            var loader = new StateMachineLoader<T, U>();
            loader.SetCurrentState(saver.CurrentStateId);
            loader.SetEvents(saver.Events);
            loader.SetHistoryStates(saver.HistoryStates);
            loader.SetPriorityEvents(saver.PriorityEvents);

            await machine.Load(loader);
        }
    }
```

but basically the same questions persists..

**Comment by ursenzler** [comment]
There are many ways of storing the state of the state machine so I don't provide a default implementation.
Luckily, implementing the interfaces for loading and saving is quite easy. Some docu: https://github.com/appccelerate/statemachine/blob/nullable_reference_types/documentation/persistence.md

I hope that helps.
