### ISSUE TITLE
the state machines are missing a StateEntered event

### ISSUE THREAD

**Issue by bitbonk** [appccelerate/statemachine#8]
From [Wikipedia](https://en.wikipedia.org/wiki/UML_state_machine): 

> Every state in a UML statechart can have optional entry actions, **which are executed upon entry to a state**

![uml_state_machine_fig5](https://cloud.githubusercontent.com/assets/418030/18025275/2da88aa8-6c25-11e6-9a96-1e4e78e69ee4.png)

With the current implementation, it looks like I don't have a way to to report (e.g. to the UI) that the current state is "heating" while the entry action is still executing. The `TransitionCompleted` is only raised _after_ the enter action was executed and in the `TransitionBegin` event, I don't have a way to tell what the target state of the transition will be.

To stay with the example from Wikipedia, I would like to report to the user that state _door_open_ was entered so the user knows that all the stuff is going to happen that needs to be done in this state (i.e. turning the lamp on - which could be a complex procedure in itself).

For that we'd need something like `StateEntered` or `StateChanged` event.

**Comment by ursenzler** [comment]
You can use an EntryAction on the state heating. See http://www.appccelerate.com/statemachineactions.html

**Comment by bitbonk** [comment]
That's what I do, but the `TransitionCompleted` event is fired **after** that entry action was executed.

**Comment by ursenzler** [comment]
The state machine is in the heating state when all transition actions are executed. While executing a transition with all its actions, the state machine is not in a state. Therefore it is correct that the state machine is really in the heating state after the transition is completed. But from your question, I guess that you have a problem that cannot be solved this way.
In all the state machines I wrote, I never had to use the transition completed event to achieve the required functionality, the event is there for debugging and tracing. 
I think it would help to know your real problem so that I can show you how I would solve it. Or should I code the example of the heater for you with the Appccelerate state machine? Would that help?

**Comment by bitbonk** [comment]
I am trying to use your state machine to control a vacuum chamber that processes a silicon wafers (the domain is semiconductor fab- and tool automation). When a wafer arrives at the gate of the process module the chamber goes into the state "opening gate". When it is in that state, it will do "a lot of stuff" to actually open the gate. This "stuff" is done in the enter action.

For diagnosis purposes I must provide a UI, that visualizes the current state in realtime. So when the state machine is in state "opening gate" I need to report that to the UI, so the user knows that it is currently doing what needs to be done to open the gate. Once a sensor reports that the gate is fully open, it will transition to the state "gate opened" and I need to report that to the UI too.

I guess my main problem is that I need to report the state of the sate machine in a finer grained detail than it is currently possible with the events you provide.

I agree that `TransitionCompleted` should be executed after the transition actions (`.Execute()`) are done. But I would think that enter actions (`ExecuteOnEntry()`) is not part of the transition itself. When the enter action is executed that state machine is already in that new state. And it would be cool to get notified when the state machine enters a new state. Hence my idea to introduce a `StateEntered`event that is raised before the enter action is executed.

**Comment by ursenzler** [comment]
I"ll try to reply tomorrow with an example how I would solve this.


bit bonk <notifications@github.com> schrieb am Sa., 27. Aug. 2016 um 23:49:

**Comment by ursenzler** [comment]
Here the example (it's not complete but I hope it shows enough):
```csharp
namespace Appccelerate.StateMachine
{
    public interface IListener
    {
        void NotifyOpening();
        void NotifyOpened();
        void NotifyClosing();
        void NotifyClosed();
    }

    public class Example
    {
        public enum States { Closed, Opening, Open, Closing }
        public enum Events { Opening, Opened, Closing, Closed }

        private readonly IListener listener;
        private readonly IStateMachine<States, Events> machine;

        public Example(
            IListener listener, // the UI implements this interface to be notified. Alternatively, you could use events
            IStateMachine<States, Events> machine) // inject for simpler testing
        {
            this.listener = listener;
            this.machine = machine;

            this.DefineMachine();

            this.machine.Start();
        }

        public void Open() // call from outside to start opening door
        {
            this.machine.Fire(Events.Opening);
        }
        
        private void DefineMachine()
        {
            this.machine.In(States.Closed)
                .On(Events.Opening).Goto(States.Opening).Execute(this.ExecuteOpeningActions);

            this.machine.In(States.Opening)
                .On(Events.Opened).Goto(States.Open).Execute(this.ExecuteOpenActions);

            /* other transitions */
        }

        private void ExecuteOpeningActions()
        {
            this.listener.NotifyOpening();

            /* do whatever has to be done during opening */
            
            this.machine.Fire(Events.Opened); // switch to state opened when done
                                              // assumption that you use a passive state machine, otherwise the state machine need more transitions because 
                                              // multiple threads could send events and we cannot savely assume that we can call Opened on
                                              // the state machine from within the Opening actions.

        }

        private void ExecuteOpenActions()
        {
            this.listener.NotifyOpened();
        }
    }
}
```

**Comment by bitbonk** [comment]
Thank you for investing your time to provide such a detailed example. Although this solution would work, it would however result in quite a lot of code duplication or boilerplate code. For each and every state that my state machine has, I would have to introduce the appropriate `Notify*` method in the `IListener` interface and I would have have the responsibility to call it at the beginning of each and every action manually. I would expect that the framework provides with infrastructure for this (in my mind) common use case. Especially since it seems so trivial to introduce a `StateEntered` event.

You already provide infrastructure to statically "visualize" the whole state machine though the `IStateMachineReport` interface. Why not go the extra mile to also support live updates for it. Provide APIs so I can highlight the current state, the current transition, the current guard (the guard that was applied), the currently executing action etc. in my WPF visualization? Would that be worth a separate feature request here on github?

But your example brought up another idea. I could refactor my state machine such that I have 

**(state)closed** --> **(event)opening** --> **(state)opening**

Now I can do "the stuff that needs to be done to open the gate" in the transition action (`Execute()`) of the **opening** transition/event and I could use the `TransitionBegin` event to report to the UI that the gate is opening before the actions are executed (using `TransitionEventArgs.EventId`).

**Comment by ursenzler** [comment]
I think an extension could do the job, but I have to think about it.

**Comment by ursenzler** [comment]
http://www.appccelerate.com/statemachineextensions.html
