### ISSUE TITLE
.net core?

### ISSUE THREAD

**Issue by ursenzler** [appccelerate/statemachine#9]
Try if the state machine can target .net core.

**Comment by philippdolder** [comment]
I'm giving it a try

**Comment by philippdolder** [comment]
Experimental package is available
https://www.myget.org/feed/appccelerate/package/nuget/Appccelerate.StateMachine/2.17.0-commitdc50fd10

Make sure to **explicitly** install the matching Appccelerate.Fundamentals package 
https://www.myget.org/feed/appccelerate/package/nuget/Appccelerate.Fundamentals/3.3.0-commitea8ae2ca

**Comment by philippdolder** [comment]
closed by [this PR](https://github.com/appccelerate/statemachine/pull/16)
